AllCops:
  TargetRubyVersion: 2.6

Metrics/AbcSize:
  Enabled: true
  Max: 25

Metrics/MethodLength:
  Enabled: true
  Max: 18

Style/Semicolon:
  Enabled: true
  Exclude:
    - "lib/net/tofu/response.rb"

Style/SingleLineMethods:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
